### ISSUE TITLE
🐞Cannot start Kafka server since `meta.properties` could not be loaded

### ISSUE THREAD

**Issue by bmgante** [opennms-forge/ansible-opennms#50]
When executing kafka role, the kafka service does not start due to the error:

```
[2024-05-08 14:48:54,082] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
org.apache.kafka.common.KafkaException: Cannot start server since `meta.properties` could not be loaded from /var/log/kafka/combined-logs
	at kafka.server.KafkaRaftServer$.initializeLogDirs(KafkaRaftServer.scala:145)
	at kafka.server.KafkaRaftServer.<init>(KafkaRaftServer.scala:57)
	at kafka.Kafka$.buildServer(Kafka.scala:83)
	at kafka.Kafka$.main(Kafka.scala:91)
	at kafka.Kafka.main(Kafka.scala)
```

File files below do not have the right permissions:

```
[root@stldnonmswt01 combined-logs]# ls -lrth
total 8.0K
-rw-r-----. 1 root root  86 May  8 14:48 meta.properties
-rw-r-----. 1 root root 249 May  8 14:48 bootstrap.checkpoint
```

**Comment by bmgante** [comment]
Adding this task fixes the problem:

```
- name: Set ownership and permissions
  file:
    path: /var/log/kafka/combined-logs
    owner: kafka
    group: kafka
    recurse: yes
    mode: "0755"
  tags:
    - opennms
    - kafka
    - config
```

**Comment by indigo423** [comment]
Thank @bmgante for investigating that problem and providing a solution. Can you take a look at the PR and just see if that makes sense to you? Sorry for the late response.
